using Microsoft.AspNetCore.Mvc;
using Tourism.DataAccess;
using Tourism.Models;

namespace Tourism.Controllers
{
    public class StatesController : Controller
    {
        private readonly TourismContext _context;

        public StatesController(TourismContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var states = _context.States.ToList();
            return View(states);
        }

        [Route("states/{stateId:int}")]
        public IActionResult Show(int stateId)
        {
            var state = _context.States.Find(stateId);
            return View(state);
        }

        public IActionResult New()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(State stateCreated)
        {
            //Take the movie sent in the request and save it to the database
            _context.States.Add(stateCreated);
            _context.SaveChanges();

            // The id generated by the database is now on the object we added to the context
            var newStateId = stateCreated.Id;

            // Redirect to our route /movies/show and pass in the newMovieId for the id parameter
            return RedirectToAction("show", new { stateId = newStateId });
        }
    }
}
